name: Run Parallel

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  run-tests:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install forge dependencies
      run: forge install

    - name: Run forge test for the file
      run: forge test --no-match-contract FFI
      env:
        RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
        CHAIN_ID: ${{ secrets.CHAIN_ID }}
